import type { Metadata } from 'next'
import "./globals.css"
import styles from '@/assets/css/app.module.css';
import TitleBar from '@/components/TitleBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        <div className={styles.app}>
          <TitleBar />
          <div className={styles.main}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
